apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecr-demo
  namespace: ecr-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecr-demo
  template:
    metadata:
      labels:
        app: ecr-demo
    spec:
      containers:
      - name: ecr-demo
        image: 168400405642.dkr.ecr.eu-north-1.amazonaws.com/myapp-ecr-demo:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ecr-demo-svc
  namespace: ecr-demo
spec:
  selector:
    app: ecr-demo
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
